# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-18 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180702_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='twitchusername',
            field=models.CharField(max_length=64, null=True, verbose_name=b'Twitch Username (For CrowdControl coins)'),
        ),
    ]
