# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_donation_twitchusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paypalreturntext',
            field=models.TextField(blank=True, null=True, verbose_name=b'PayPal Return Text'),
        ),
        migrations.AddField(
            model_name='event',
            name='recieverimage',
            field=models.CharField(max_length=128, null=True, verbose_name=b'Reciever Image (logo)'),
        ),
    ]
