# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-24 19:35
from __future__ import unicode_literals

from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    Events = apps.get_model('tracker', 'event')
    for event in Events.objects.all().iterator():
        event.use_crowdcontrol = False
        event.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200524_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_crowdcontrol',
            field=models.BooleanField(null=True, default=False, verbose_name=b'Use CrowdControl integration'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='twitchusername',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Twitch Username (For CrowdControl coins)'),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='event',
            name='use_crowdcontrol',
            field=models.BooleanField(null=False, default=False, verbose_name=b'Use CrowdControl integration')
        ),
    ]


