# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-01-31 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_add_cc_event_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrun',
            name='external_id',
            field=models.TextField(blank=True, help_text=b'Id used to identified run in external system.', max_length=128, null=True, verbose_name=b'External Id'),
        ),
        migrations.AddField(
            model_name='speedrun',
            name='show_on_start',
            field=models.BooleanField(default=False, help_text=b'Advertise the event on the start page', verbose_name=b'Show on start page'),
        ),
    ]
