# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-01-31 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_add_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedrun',
            name='show_on_start',
        ),
        migrations.AddField(
            model_name='event',
            name='show_on_start',
            field=models.BooleanField(default=False, help_text=b'Advertise the event on the start page', verbose_name=b'Show on start page'),
        ),
    ]
