# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_event_horaro_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='horaro_name',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
    ]
