# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-01-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20210222_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='oengus_name',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
    ]
