# Generated by Django 2.0.4 on 2018-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_add_tiltify_horaro_twitch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name', 'alpha2'), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='countryregion',
            options={'ordering': ('country', 'name'), 'verbose_name': 'Country Region', 'verbose_name_plural': 'Country Regions'},
        ),
        migrations.AlterModelOptions(
            name='runner',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='prize',
            name='auto_tickets',
            field=models.BooleanField(default=False, help_text='Counts all qualifying donations towards tickets automatically', verbose_name='Automatic Tickets'),
        ),
    ]
